spring.application.name=backend
server.port=8081



spring.datasource.url=jdbc:postgresql://ep-rough-union-a1d772r9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RN7EJoCwxy3d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=253827365551-vsbj7rq1gk4tj1pl6t193t6bfbv4bgfa.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email


######################

# spring.application.name=backend
# server.port=8081

# spring.datasource.url=jdbc:postgresql://ep-rough-union-a1d772r9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_RN7EJoCwxy3d
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect (Not needd)

# spring.security.oauth2.client.registration.google.client-id=253827365551-vsbj7rq1gk4tj1pl6t193t6bfbv4bgfa.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=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
# spring.security.oauth2.client.registration.google.scope=openid,profile,email

# spring.application.name=backend
# server.port=8081

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
# spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
# spring.security.oauth2.client.registration.google.scope=openid,profile,email